# Copyright 2024 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Update parent artifact deletion

Revision ID: 7354a3351669
Revises: e77074ae071f
Create Date: 2025-08-03 17:08:12.780939

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "7354a3351669"
down_revision = "e77074ae071f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "model_endpoints",
        "mode",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "model_endpoints",
        "mode",
        existing_type=sa.Integer(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
