{
 "title": "Model Monitoring - Details",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "PROJECT", "label": "Project", "query": "target_endpoint=list_projects" },
   {
    "name": "MODELENDPOINT",
    "label": "Model Endpoint",
    "query": "target_endpoint=list_endpoints;project=$PROJECT"
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "description": "A summary table of the selected model endpoint, with the following fields:\n\n- **Name**: The model endpoint name.\n- **Endpoint ID**: The unique identifier for the model endpoint.\n- **Function**: The name of the function.\n- **Model Class**: The model object class (e.g., `SKLearnModelServer`).\n- **Error Count**: The total number of errors.\n- **Sampling Percentage**: The sampling rate percentage. By default (100), all events are sampled.\n- **Drift Status**: The drift status indicator, currently based on the `general_drift` result from the histogram default application.\n\nNote that this table reflects the current system status and is not influenced by the selected time range.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "target_endpoint=list_endpoints;project=$PROJECT;uids=$MODELENDPOINT",
     "type": "table"
    }
   ]
  },
  {
   "title": "Drift Analysis",
   "type": "timeseries",
   "description": "Drift value over time, based on the general_drift result from the histogram data drift application. The drift value is calculated as the average of Total Variance Distance and Hellinger Distance. The default thresholds are 0.5 for potential drift and 0.7 for detected drift.\nFor more information about the default drift analysis please visit:",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 3 },
   "targets": [
    {
     "target": "backend=tsdb;\ncontainer=users;\ntable=pipelines/$PROJECT/monitoring-apps/app-results/;\nfilter=endpoint_id=='$MODELENDPOINT' AND application_name=='histogram-data-drift';",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Overall Drift Analysis by Time",
   "type": "timeseries",
   "description": "This chart shows the metrics of the default histogram application over time. For more details on these metrics, please visit:",
   "gridPos": { "h": 11, "w": 10, "x": 13, "y": 3 },
   "targets": [
    {
     "target": "backend=tsdb;\ncontainer=users;\ntable=pipelines/$PROJECT/monitoring-apps/metrics/;\nfilter=endpoint_id=='$MODELENDPOINT' AND metric_name=='hellinger_mean';",
     "type": "table"
    },
    {
     "target": "backend=tsdb; container=users; table=pipelines/$PROJECT/monitoring-apps/metrics/; filter=endpoint_id=='$MODELENDPOINT' AND metric_name=='tvd_mean';",
     "type": "table"
    },
    {
     "target": "backend=tsdb; container=users; table=pipelines/$PROJECT/monitoring-apps/metrics/; filter=endpoint_id=='$MODELENDPOINT' AND metric_name=='kld_mean';",
     "type": "table"
    }
   ]
  },
  {
   "title": "Incoming Features",
   "type": "graph",
   "description": "Data sampling of the model's input and output over time.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "backend=tsdb;\ncontainer=users;\ntable=pipelines/$PROJECT/model-endpoints/events;\nfilter=endpoint_id=='$MODELENDPOINT'  AND record_type=='endpoint_features';",
     "type": "timeserie"
    }
   ]
  }
 ]
}